version: '3.8'
services:
  gateway:
    build: ./gateway
    environment:
      - SHAREIT_SERVER_URL=http://server:9090
      - TZ=Europe/Moscow
    ports:
      - "8080:8080"


  server:
    build: ./server
    container_name: server
    depends_on:
     - gateway
    environment:
      - TZ=Europe/Moscow
    ports:
    - "9090:9090"


