DROP TABLE IF EXISTS ITEM_TABLE CASCADE;
DROP TABLE IF EXISTS USER_TABLE CASCADE;
DROP TABLE IF EXISTS BOOKING_TABLE CASCADE;
DROP TABLE IF EXISTS BOOKING_USER_TABLE CASCADE;
DROP TABLE IF EXISTS ITEM_BOOKING_TABLE CASCADE;

CREATE TABLE IF NOT EXISTS USER_TABLE
(
    ID    BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME  VARCHAR(100),
    EMAIL VARCHAR(100),
    CONSTRAINT UNIQUE_EMAIL UNIQUE (EMAIL)
);

CREATE TABLE IF NOT EXISTS ITEM_TABLE
(
    ID           BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME         VARCHAR(100),
    DESCRIPTION  TEXT,
    IS_AVAILABLE BOOLEAN,
    OWNER_ID     BIGINT DEFAULT NULL,
    REQUEST      BIGINT DEFAULT NULL,
    FOREIGN KEY (OWNER_ID) REFERENCES USER_TABLE (ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS BOOKING_TABLE
(
    ID         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    START_DATE DATE,
    END_DATE   DATE,
    ITEM_ID    BIGINT,
    USER_ID    BIGINT,
    STATUS     VARCHAR(64),
    FOREIGN KEY (USER_ID) REFERENCES USER_TABLE (ID) ON DELETE CASCADE,
    FOREIGN KEY (ITEM_ID) REFERENCES ITEM_TABLE (ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS BOOKING_USER_TABLE
(
    USER_ID    BIGINT,
    BOOKING_ID BIGINT,
    FOREIGN KEY (USER_ID) REFERENCES USER_TABLE (ID) ON DELETE CASCADE,
    FOREIGN KEY (BOOKING_ID) REFERENCES BOOKING_TABLE (ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ITEM_BOOKING_TABLE
(
    ITEM_ID    BIGINT,
    BOOKING_ID BIGINT,
    FOREIGN KEY (ITEM_ID) REFERENCES ITEM_TABLE (ID) ON DELETE CASCADE,
    FOREIGN KEY (BOOKING_ID) REFERENCES BOOKING_TABLE (ID) ON DELETE CASCADE
);
