DROP TABLE IF EXISTS ITEM_TABLE CASCADE;
DROP TABLE IF EXISTS USER_TABLE CASCADE;

CREATE TABLE IF NOT EXISTS USER_TABLE
(
    ID    BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME  VARCHAR(100),
    EMAIL VARCHAR(100),
    CONSTRAINT UNIQUE_EMAIL UNIQUE (EMAIL)
);

CREATE TABLE IF NOT EXISTS ITEM_TABLE
(
    ID           BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME         VARCHAR(100),
    DESCRIPTION  TEXT,
    IS_AVAILABLE BOOLEAN,
    OWNER_ID     BIGINT DEFAULT NULL,
    REQUEST      BIGINT DEFAULT NULL

);
